### ISSUE TITLE
Using JSON-LD to communicate use of simplestyle-spec

### ISSUE THREAD

**Issue by sgillies** [mapbox/simplestyle-spec#16]
What does it mean if I find a "stroke" item in a feature's "properties"? What am I as a GeoJSON reader supposed to do? I think that JSON-LD provides a way to answer these questions, at least to JSON-LD aware readers: it adds optional namespaces and defining links to the dog's breakfast that is a Feature.properties. For example, adding a @context like this:

```
{ "@context":
  { "title": "http://schema.org/name",
    "description": "http://schema.org/description",
    "marker-size": "https://github.com/mapbox/simplestyle-spec/tree/master/1.1.0/#marker-size",
    "marker-symbol": "https://github.com/mapbox/simplestyle-spec/tree/master/1.1.0/#marker-symbol",
    "marker-color": "https://github.com/mapbox/simplestyle-spec/tree/master/1.1.0/#marker-color",
    "stroke": "https://github.com/mapbox/simplestyle-spec/tree/master/1.1.0/#stroke",
    "stroke-opacity": "https://github.com/mapbox/simplestyle-spec/tree/master/1.1.0/#stroke-opacity",
    "stroke-width": "https://github.com/mapbox/simplestyle-spec/tree/master/1.1.0/#stroke-width",
    "fill": "https://github.com/mapbox/simplestyle-spec/tree/master/1.1.0/#fill",
    "fill-opacity": "https://github.com/mapbox/simplestyle-spec/tree/master/1.1.0/#fill-opacity"},
  "type": "FeatureCollection",
  ... }
```

defines the terms in a machine readable way and gives links that developers can follow to find out more about these new terms that are popping up in their data. It's also decoupled from the contents of the feature collection so that developers can ignore it if they prefer.

The question "is this GeoJSON file I have a simplestype-spec GeoJSON file?" becomes "are there simplestyle-spec identifiers in its @context?" A much easier question for applications to ask and answer.

Related: I'm putting together a vocabulary and default GeoJSON-LD context at https://github.com/geojson/geojson-ld.

**Comment by bhousel** [comment]
closing as stale
