### ISSUE TITLE
ArcMap Cannot Use Dashes

### ISSUE THREAD

**Issue by reyemtm** [mapbox/simplestyle-spec#19]
Love the spec but in my workflow I have to go back in and edit the field names in my geojson/csv/etc to add the dashes - would be great if it would accept the same field names with no dashes, or with underscores in addition to dashes.

Thanks

**Comment by tmcw** [comment]
It's unlikely that we'll support dashes in simplestyle-spec - it would be a serious breaking change, and the current property names are compatible with nearly all systems but ArcMap.

This will be something to keep in mind for specs beyond simplestyle-spec, but the change is severe enough that we wouldn't want to push a 2.0.0 only for it.

**Comment by reyemtm** [comment]
Ok, that's fine, but I think you mean you will not support underscores. To be clear, I am talking about "marker-color" and "marker-symbol", which require dashes. Also, although fields with dashes may be compatible with 'nearly all systems', lacking support for the one major desktop GIS platform seems like an oversight.

**Comment by tmcw** [comment]
Yes: it is an oversight. 3 years ago when we first authored this draft we didn't have the means to review every platform and application and certainly didn't expect a flagship product to be incapable of dashes. If we had known that then, we may have reconsidered dashes.

But it's unlikely that would have happened: simplestyle-spec was authored in 2012, 2+ years before ArcGIS Online supported GeoJSON at all, and I don't see [any information about GeoJSON support in ArcGIS Desktop](http://resources.arcgis.com/en/help/main/10.1/index.html#//018m00000002000000) today, in mid 2015. Designing this GeoJSON-embedded style specification to be compatible with software that didn't/doesn't support GeoJSON via the transport of being converted into Shapefiles or something else seems improbable in hindsight.

Now that the style specification has quite a bit of adoption and making a breaking change would be extremely inconvenient for its many implementations, it seems more reasonable that Esri would improve their software than we would degrade our specification to match its flaws.

**Comment by reyemtm** [comment]
Agreed. For reference here is info on [characters and field names in ArcMap](http://support.esri.com/cn/knowledgebase/techarticles/detail/23087).
