### ISSUE TITLE
Color Rules?

### ISSUE THREAD

**Issue by MKergall** [mapbox/simplestyle-spec#20]
From the spec: 
// COLOR RULES
// Colors can be in short form:
//   "#ace"
// or long form
//   "#aaccee"

Could this be a little bit more precise, like: "hexBinary value: #rgb or #rrggbb"
Or is it #bbggrr, as in KML?

**Comment by tmcw** [comment]
It's `#rrggbb`, like CSS and everything except for KML (there may be another thing that does KML-style colors, but I have not seen it).
