### ISSUE TITLE
New Maki icons not supported by simplestyle-spec

### ISSUE THREAD

**Issue by jbhoward-dublin** [mapbox/simplestyle-spec#26]
Some icons in the current Maki icon set are not supported by the simplestyle-spec. For example, the  'castle' icon, specified as ```"marker":"castle"``` issues a request for

```https://a.tiles.mapbox.com/v4/marker/pin-m-castle+3366ff.png?access_token={}```

and return HTTP 400 and error message

```{"message":"Marker \"pin-m-landmark+3366ff\" is invalid."}```

Are there plans to update simplestyle-spec to accommodate all icons in the current icon set?

**Comment by samanpwbb** [comment]
Different implementations of simplestyle-spec will support different icons.

The v4 marker API will not support additional icons beyond what it supports now. It is pinned to this version of maki: https://github.com/mapbox/maki/tree/v0.5.0 indefinitely.
