### ISSUE TITLE
Update URL

### ISSUE THREAD

**Issue by pnorman** [mapbox/simplestyle-spec#30]
The github project references `http://mapbox.com/developers/simplestyle/` but this redirects to `https://www.mapbox.com/help/how-mapbox-works/`

**Comment by pnorman** [comment]
https://www.mapbox.com/help/define-simplestyle/ links to the same page.

That URL redirects through the following list of URLs

- https://mapbox.com/guides/an-open-platform/#simplestyle 
- https://www.mapbox.com/guides/an-open-platform/ 
- /help/an-open-platform
- /help/an-open-platform/
- /help/how-mapbox-works/

The redirects are a mix of HTTP headers and meta tags.

**Comment by bhousel** [comment]
Thanks @pnorman for letting us know - I've removed the URL from the project page.
 
We aren't really using this much anymore at Mapbox, but there are still a handful of [implementations](https://github.com/mapbox/simplestyle-spec/wiki/Implementations) out in the wild that support it.

**Comment by pnorman** [comment]
Aren't you using it in Mapbox.js?

I think we're pulling it in via geojson-mapnikify, as well as using it in [kartotherian/geoshapes](https://github.com/kartotherian/geoshapes). I added our use to the implementations page.

**Comment by bhousel** [comment]
> Aren't you using it in Mapbox.js?

Yes we're using it in a few things but not enough for it to have its own support page.

AFAIK, it's still used in geojson.io, classic Mapbox.js, and our static maps API (which supports a subset of simplestyled geojson overlay over a static map - see https://github.com/mapbox/simplespec-to-gl-style )

It's not _directly_ supported in Mapbox GL, but developers can use an [identity property function](https://github.com/mapbox/mapbox-gl-js/issues/5351) to pass the simplestyle properties through to the Mapbox GL renderer.
