### ISSUE TITLE
Leaflet-simplestyle connector

### ISSUE THREAD

**Issue by tmcw** [mapbox/simplestyle-spec#6]
Should be somewhat simple to implement.

**Comment by newmanw** [comment]
Not 100% sure what this means:

'This is in mmg's tracker and is blocked by Leaflet limitations, aka leafitations.'

Regardless, looks to be closed a while ago, are limitations still present?

**Comment by tmcw** [comment]
[Mapbox.js](https://github.com/mapbox/mapbox.js)'s featureLayer is the implementation of this.

**Comment by newmanw** [comment]
Very cool, thanks!!!
